---
#-------------------------------
# General Site Settings

title: HO MINH MAN
logo:
#author: themefisher
#description: this is meta description
email: hmman.ct@gmail.com
phone: +84 344 565 833
address: Tan Binh District, Ho Chi Minh City
github_url: https://github.com/homanad
linkedin_url: https://www.linkedin.com/in/manhominh/
copyright: Copyright &copy; 2020 Designed by [Themefisher](https://themefisher.com) & Developed by [Getjekyllthemes](https://getjekyllthemes.com)

menu:
  - { name: About, link: "/about" }
  - { name: Experience, link: "/experience" }
  - { name: Projects, link: "/projects" }
  - { name: Blogs, link: "/blogs" }


#-------------------------------
# Comment Section (Disqus)

disqus-identifier: # Add your shortname for Disqus Comment. For example mr-brown

#-------------------------------
# Hero Section

hero:
  hero-title: I’m an<br/>Android Developer

social:
  - { icon: "ti-github", link: "https://github.com/homanad" }
  - { icon: "ti-linkedin", link: "https://www.linkedin.com/in/manhominh/" }

#-------------------------------
# About (Section and Page)

# About Section
blurb: I'm an Android Developer with 6 years of experience, always researching and learning new techniques, ready to learn new things to meet work requirements, always keeping the mindset of testers and users to ensure the functions operate with the least possible problems.

blurb-btn-link: "/about"
blurb-btn-name: know more

#-------------------------------
# Skills Section

skills-title: Skills
skills:
  - { name: Kotlin/Java, color: "#fdb157", value: "100%" }
  - { name: MVVM/MVI, color: "#fdb157", value: "100%" }
  - { name: Clean Architecture, color: "#9473e6", value: "100%" }
  - { name: Jetpack components, color: "#bdecf6", value: "100%" }
  - { name: Material components, color: "#bdecf6", value: "100%" }
  - { name: Dark & Light themes, color: "#bdecf6", value: "100%" }
  - { name: Multiple screen sizes, color: "#ffbcaa", value: "100%" }
  - { name: Custom view, color: "#ffbcaa", value: "100%" }
  - { name: Dependency Injection, color: "#ffbcaa", value: "100%" }
  - { name: Jetpack Compose, color: "#ffbcaa", value: "100%" }
  - { name: Baseline Profile, color: "#ffbcaa", value: "100%" }
  - { name: Unit & UI testing, color: "#ffbcaa", value: "100%" }
  - { name: RxJava/Android, color: "#ffbcaa", value: "100%" }
  - { name: Kotlin Coroutines, color: "#ffbcaa", value: "100%" }
  - { name: Kotlin Flows, color: "#ffbcaa", value: "100%" }
  - { name: Firebase services, color: "#ffbcaa", value: "100%" }
  - { name: Play features/assets, color: "#ffbcaa", value: "100%" }

#-------------------------------
# Exprerience Section

experience-title: Experience
experience:
  - {
    name: CELEBe,
    icon: "assets/images/experience/celebe.png",
    url: "/experience/celebe",
    date: "May 2023 - Present",
    organization: "Android Developer",
  }
  - {
    name: AnySES,
    icon: "assets/images/experience/anyses.png",
    url: "/experience/anyses",
    date: "Nov 2021 - May 2023",
    organization: "Android Team Leader",
  }
  - {
    name: Samsung HCMC R&D Center,
    icon: "assets/images/experience/samsung.png",
    url: "/experience/samsung",
    date: "Nov 2019 - Oct 2021",
    organization: "Android Developer",
  }
  - {
    name: TMA Solutions,
    icon: "assets/images/experience/tma.png",
    url: "/experience/tma",
    date: "Mar 2019 - Oct 2019",
    organization: "Java Developer",
  }

#-------------------------------
# Education Section

education-title: Education
education:
  - {
      name: Can Tho University,
      date: "Sep 2015 - Sep 2019",
      organization: "Information Technology (GPA 3.11/4)",
    }

project-items:
  - image: "assets/images/portfolio/compose_search_bar.webp"
    url: "/projects/compose-search-bar"
    title: "Compose Search Bar"

  - image: "assets/images/portfolio/compose_charts.webp"
    url: "/projects/compose-charts"
    title: "Compose charts"

  - image: "assets/images/portfolio/styleable_seek_bar.webp"
    url: "/projects/styleable-seek-bar"
    title: "Styleable Seek Bar"

  - image: "assets/images/portfolio/lined_edit_text.webp"
    url: "/projects/lined-edit-text"
    title: "Lined Edit Text"

  - image: "assets/images/portfolio/auto_dimensions.webp"
    url: "/projects/auto-dimensions"
    title: "Auto Dimensions"

  - image: "assets/images/portfolio/flex_image_view.jpg"
    url: "/projects/flex-image-view"
    title: "Flex Image View"